services:
  boardgame:
    # Image is only used locally, to avoid building all services individually
    image: boardgame:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "uvicorn src.app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
